using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public static class map0 
{
	public static Vector2 MapSize;
	public static Vector2 PlayerStart; 
	public static List<Vector2> LootCrates;
	public static List<Vector2> EnemyStart;
	public static Dictionary<TilesName, List<Vector2>> dict;

	public static void init(){
		MapSize = new Vector2(20,20);
		PlayerStart = new Vector2(1,1);
		EnemyStart = new List<Vector2>();
		LootCrates = new List<Vector2>();
//		EnemyStart.Add(new Vector2(6,6));
//		EnemyStart.Add(new Vector2(5,5));
//		EnemyStart.Add(new Vector2(18,19));
//		EnemyStart.Add(new Vector2(13,15));
//		EnemyStart.Add(new Vector2(0,12));
//		EnemyStart.Add(new Vector2(14,6));
//		EnemyStart.Add(new Vector2(11,11));
//		EnemyStart.Add(new Vector2(10,19));
		LootCrates.Add (new Vector2 (2, 2));
		LootCrates.Add (new Vector2 (5, 5));
		LootCrates.Add (new Vector2 (19, 0));
		LootCrates.Add (new Vector2 (3, 2));
		LootCrates.Add (new Vector2 (3, 2));
		LootCrates.Add (new Vector2 (4, 2));
		LootCrates.Add (new Vector2 (5, 2));
		LootCrates.Add (new Vector2 (6, 2));
		dict = new Dictionary<TilesName, List<Vector2>> ();
		dict [TilesName.Impassable] = new List<Vector2> ();
		dict [TilesName.Difficult] = new List<Vector2> ();
		dict [TilesName.Finish] = new List <Vector2> ();

		dict[TilesName.Impassable].Add(new Vector2(0,6));
		dict[TilesName.Impassable].Add(new Vector2(1,6));
		dict[TilesName.Impassable].Add(new Vector2(2,6));
		dict[TilesName.Impassable].Add(new Vector2(3,6));
		dict[TilesName.Impassable].Add(new Vector2(4,4));
		dict[TilesName.Impassable].Add(new Vector2(5,4));
		dict[TilesName.Impassable].Add(new Vector2(6,4));
		dict[TilesName.Impassable].Add(new Vector2(7,4));
		dict[TilesName.Impassable].Add(new Vector2(8,4));
		dict[TilesName.Impassable].Add(new Vector2(4,5));
		dict[TilesName.Impassable].Add(new Vector2(4,6));
		dict[TilesName.Impassable].Add(new Vector2(8,5));
		dict[TilesName.Impassable].Add(new Vector2(8,6));
		dict[TilesName.Impassable].Add(new Vector2(3,0));
		dict[TilesName.Impassable].Add(new Vector2(9,6));
		dict[TilesName.Impassable].Add(new Vector2(9,7));
		dict[TilesName.Impassable].Add(new Vector2(10,7));
		dict[TilesName.Impassable].Add(new Vector2(11,7));
		dict[TilesName.Impassable].Add(new Vector2(11,8));
		dict[TilesName.Impassable].Add(new Vector2(12,8));
		dict[TilesName.Impassable].Add(new Vector2(13,9));
		dict[TilesName.Impassable].Add(new Vector2(4,13));
		dict[TilesName.Impassable].Add(new Vector2(5,13));
		dict[TilesName.Impassable].Add(new Vector2(6,13));
		dict[TilesName.Impassable].Add(new Vector2(7,13));
		dict[TilesName.Impassable].Add(new Vector2(8,13));
		dict[TilesName.Impassable].Add(new Vector2(9,13));
		dict[TilesName.Impassable].Add(new Vector2(10,13));
		dict[TilesName.Impassable].Add(new Vector2(11,13));
		dict[TilesName.Impassable].Add(new Vector2(12,13));
		dict[TilesName.Impassable].Add(new Vector2(13,13));
		dict[TilesName.Impassable].Add(new Vector2(14,13));
		dict[TilesName.Impassable].Add(new Vector2(15,13));
		dict[TilesName.Impassable].Add(new Vector2(16,13));
		dict[TilesName.Impassable].Add(new Vector2(17,13));
		dict[TilesName.Impassable].Add(new Vector2(18,13));
		dict[TilesName.Impassable].Add(new Vector2(19,13));
		dict[TilesName.Difficult].Add(new Vector2(3,1));
		dict[TilesName.Difficult].Add(new Vector2(3,2));
		dict[TilesName.Difficult].Add(new Vector2(3,3));
		dict[TilesName.Difficult].Add(new Vector2(4,0));
		dict[TilesName.Difficult].Add(new Vector2(4,1));
		dict[TilesName.Difficult].Add(new Vector2(4,2));
		dict[TilesName.Difficult].Add(new Vector2(4,3));
		dict[TilesName.Difficult].Add(new Vector2(5,0));
		dict[TilesName.Difficult].Add(new Vector2(5,1));
		dict[TilesName.Difficult].Add(new Vector2(5,2));
		dict[TilesName.Difficult].Add(new Vector2(5,3));
		dict[TilesName.Difficult].Add(new Vector2(14,6));
		dict[TilesName.Difficult].Add(new Vector2(15,6));
		dict[TilesName.Difficult].Add(new Vector2(16,6));
		dict[TilesName.Difficult].Add(new Vector2(17,6));
		dict[TilesName.Difficult].Add(new Vector2(18,6));
		dict[TilesName.Difficult].Add(new Vector2(19,6));
		dict[TilesName.Difficult].Add(new Vector2(14,7));
		dict[TilesName.Difficult].Add(new Vector2(15,7));
		dict[TilesName.Difficult].Add(new Vector2(16,7));
		dict[TilesName.Difficult].Add(new Vector2(17,7));
		dict[TilesName.Difficult].Add(new Vector2(18,7));
		dict[TilesName.Difficult].Add(new Vector2(19,7));
		dict[TilesName.Difficult].Add(new Vector2(14,8));
		dict[TilesName.Difficult].Add(new Vector2(15,8));
		dict[TilesName.Difficult].Add(new Vector2(16,8));
		dict[TilesName.Difficult].Add(new Vector2(17,8));
		dict[TilesName.Difficult].Add(new Vector2(18,8));
		dict[TilesName.Difficult].Add(new Vector2(19,8));
		dict[TilesName.Difficult].Add(new Vector2(10,8));
		dict[TilesName.Difficult].Add(new Vector2(10,9));
		dict[TilesName.Difficult].Add(new Vector2(10,10));
		dict[TilesName.Difficult].Add(new Vector2(10,11));
		dict[TilesName.Difficult].Add(new Vector2(10,12));
		dict[TilesName.Difficult].Add(new Vector2(11,9));
		dict[TilesName.Difficult].Add(new Vector2(12,9));
		dict[TilesName.Difficult].Add(new Vector2(11,10));
		dict[TilesName.Difficult].Add(new Vector2(12,10));
		dict[TilesName.Difficult].Add(new Vector2(11,11));
		dict[TilesName.Difficult].Add(new Vector2(12,11));
		dict[TilesName.Difficult].Add(new Vector2(11,12));
		dict[TilesName.Difficult].Add(new Vector2(12,12));
		dict[TilesName.Finish].Add(new Vector2(19,19 ));

	}
}
